<a href="https://colab.research.google.com/github/VitaliPopov/C-sharp/blob/main/homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
df = pd.read_csv('kc_house_data.csv', sep=',')
stroki = df.head(5)
stroki

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

# Новый раздел

In [8]:
df['price_per_sq_lot'] = df['price'] / df['sqft_lot']
avg = df['price_per_sq_lot']
avg

0         39.274336
1         74.288870
2         18.000000
3        120.800000
4         63.118812
            ...
21608    318.302387
21609     68.811285
21610    297.852593
21611    167.504188
21612    302.044610
Name: price_per_sq_lot, Length: 21613, dtype: float64

In [ ]:
df['delta_renovated'] = 0
df.loc[df['yr_renovated'] != 0, 'delta_renovated'] = df['yr_renovated'] - df['yr_built']
#df['delta_renovared'] = df['yr_renovated'] - df['yr_built']
#renv = df['delta_renovared'] = df['delta_renovared'].apply(lambda x: x if x > 0 else 0)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price_per_sq_lot,delta_renovated
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,0,1955,0,98178,47.5112,-122.257,1340,5650,39.274336,0
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,400,1951,1991,98125,47.7210,-122.319,1690,7639,74.288870,40
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,0,1933,0,98028,47.7379,-122.233,2720,8062,18.000000,0
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,910,1965,0,98136,47.5208,-122.393,1360,5000,120.800000,0
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,0,1987,0,98074,47.6168,-122.045,1800,7503,63.118812,0

In [15]:
df['date'] = pd.to_datetime(df['date'])
df['year_sale'] = df['date'].apply(lambda x: x.date().year)
df['month_sale'] = df['date'].apply(lambda x: x.date().month)
year_ch = df['year_sale']
#year_ch = df['year'] = df['date'].apply(lambda x: int(x[:4]))
year_ch

0        2014
1        2014
2        2015
3        2014
4        2015
         ...
21608    2014
21609    2015
21610    2014
21611    2015
21612    2014
Name: year_sale, Length: 21613, dtype: int64

In [10]:
month_ch = df['month_sale']
#month_ch = df ['month']=df['date'].apply(lambda x: int(x[4:6]))
month_ch

0        10
1        12
2         2
3        12
4         2
         ..
21608     5
21609     2
21610     6
21611     1
21612    10
Name: month_sale, Length: 21613, dtype: int64

In [11]:
new = df.drop(columns=['date', 'zipcode', 'lat', 'long'], inplace=True)
new